{
 "title": "ERPNEXT APPLICATION DASHBOARD",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "environment",
    "label": "environment",
    "query": "{\"find\":\"terms\",\"field\":\"environment.keyword\",\"size\":10000}"
   },
   {
    "name": "uptime_interval",
    "label": "uptime interval",
    "query": "1m, 2m, 5m, 10m, 15m, 20m, 30m, 1h, 2h, 3h, 4h, 6h, 12h, 24h, 1d, 2d, 3d, 4d, 7d"
   },
   {
    "name": "panel_interval",
    "label": "panel Interval",
    "query": "1m, 2m, 5m, 10m, 15m, 20m, 30m, 1h, 2h, 3h, 4h, 6h, 12h, 24h, 1d, 2d, 3d, 4d, 7d"
   },
   {
    "name": "log_interval",
    "label": "log Interval",
    "query": "30d,14d,7d,4d,3d,2d,1d,24h,12h,6h,4h,3h,2h,1h,30m,20m,15m,10m,5m,2m,1m"
   }
  ]
 },
 "panels": [
  {
   "title": "URL MONITORING",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "URL (Error Count)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
     "targets": [
      {
       "alias": "URL: {{url.keyword}} TIMESTAMP: {{formatted_log_timestamp.keyword}}",
       "bucketAggs": [
        {
         "field": "url.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "response_time.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "response_time_status.keyword",
         "id": "5",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "expected_response_code.keyword",
         "id": "6",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "actual_response_code.keyword",
         "id": "7",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "response_code_status.keyword",
         "id": "8",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "email_status.keyword",
         "id": "9",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "error.keyword",
         "id": "10",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "formatted_log_timestamp.keyword",
         "id": "11",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "category.keyword",
         "id": "12",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "environment.keyword",
         "id": "13",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "timeZone": "Asia/Kolkata" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "NOT email_status: \"N/A\" AND environment: $environment\nAND \ncategory: \"ERPNEXT\"",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "URL(Success Count)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
     "targets": [
      {
       "alias": "{{category.keyword}} || {{environment.keyword}} || {{formatted_log_timestamp.keyword}} || {{url.keyword}} ",
       "bucketAggs": [
        {
         "field": "url.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "response_time.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "response_time_status.keyword",
         "id": "5",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "expected_response_code.keyword",
         "id": "6",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "actual_response_code.keyword",
         "id": "7",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "response_code_status.keyword",
         "id": "8",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "email_status.keyword",
         "id": "9",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "error.keyword",
         "id": "10",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "formatted_log_timestamp.keyword",
         "id": "11",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "category.keyword",
         "id": "12",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "environment.keyword",
         "id": "13",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "timeZone": "Asia/Kolkata" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "email_status: \"N/A\" AND environment: $environment\nAND \ncategory: \"ERPNEXT\"",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "URL Monitoring Logs (All)",
     "type": "logs",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "limit": "500" }, "type": "logs" }
       ],
       "query": "environment: $environment\nAND \ncategory: \"ERPNEXT\"",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "UPTIME",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Application Uptime",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 2 },
     "targets": [
      {
       "alias": "{{filter}} || {{category.keyword}} || {{environment.keyword}} || {{url.keyword}}",
       "bucketAggs": [
        {
         "field": "url.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "id": "5",
         "settings": {
          "filters": [
           {
            "label": "UP",
            "query": "email_status.keyword:\"N/A\""
           },
           {
            "label": "DOWN",
            "query": "email_status.keyword:\"Success\""
           }
          ]
         },
         "type": "filters"
        },
        {
         "field": "category.keyword",
         "id": "6",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "environment.keyword",
         "id": "7",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "@timestamp",
         "id": "3",
         "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "environment: $environment\nAND \ncategory: \"ERPNEXT\"",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Uptime percentage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 9, "x": 8, "y": 2 },
     "targets": [
      {
       "alias": "URL: {{url.keyword}}",
       "bucketAggs": [
        {
         "field": "url.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "uptime_percentage", "id": "1", "type": "avg" }
       ],
       "query": "environment: $environment",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Uptime percentage",
     "type": "table",
     "gridPos": { "h": 8, "w": 7, "x": 17, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "email_status.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "id": "4",
         "settings": {
          "filters": [
           {
            "label": "JFS",
            "query": "url.keyword:\"https://erpnext.jfs.in/\""
           },
           {
            "label": "CLOUD",
            "query": "url.keyword:\"https://jfs-test.frappe.cloud/\""
           },
           {
            "label": "DR JFS",
            "query": "url.keyword:\"https://drerpnext.jfs.in/\""
           }
          ]
         },
         "type": "filters"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "$uptime_interval" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "NOT url.keyword:\"https://access-jiofinance.jiofinance.in/user-maintenance\" AND environment: $environment\nAND \ncategory: \"ERPNEXT\"",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "APPLICATION MONITORING",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "APP ERROR OR EXCEPTION COUNT(SERVER TIME UTC)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "formatted_log_timestamp.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        },
        {
         "field": "log_level.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        },
        {
         "field": "log_message.keyword",
         "id": "5",
         "settings": {
          "min_doc_count": "1",
          "missing": "Check log message as message is too long",
          "order": "desc",
          "orderBy": "_term",
          "size": "0"
         },
         "type": "terms"
        },
        {
         "field": "category.keyword",
         "id": "6",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "environment.keyword",
         "id": "7",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "5m", "timeZone": "Asia/Kolkata" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "environment: $environment\nAND \ncategory: \"ERPNEXT\"",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Application Error Logs",
     "type": "logs",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "limit": "500" }, "type": "logs" }
       ],
       "query": "environment: $environment\nAND \ncategory: \"ERPNEXT\"",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "DATABASE MONITORING",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "DATABASE LONG RUNNING QUERIES",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "targets": [
      {
       "alias": "{{category.keyword}} || {{environment.keyword}} || {{log_time.keyword}} || {{query_time}} sec || {{query_statement.keyword}} || {{connection_string.keyword}}",
       "bucketAggs": [
        {
         "field": "log_time.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "log_date.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "connection_string.keyword",
         "id": "6",
         "settings": {
          "min_doc_count": "1",
          "missing": "check log as it is too long connection string",
          "order": "desc",
          "orderBy": "_term",
          "size": "0"
         },
         "type": "terms"
        },
        {
         "field": "query_statement.keyword",
         "id": "7",
         "settings": {
          "min_doc_count": "1",
          "missing": "check log as it is too long query statement",
          "order": "desc",
          "orderBy": "_term",
          "size": "0"
         },
         "type": "terms"
        },
        {
         "field": "query_time",
         "id": "8",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "user_id.keyword",
         "id": "9",
         "settings": {
          "min_doc_count": "1",
          "missing": "unknown user id",
          "order": "desc",
          "orderBy": "_term",
          "size": "10"
         },
         "type": "terms"
        },
        {
         "field": "category.keyword",
         "id": "10",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "environment.keyword",
         "id": "11",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "timeZone": "Asia/Kolkata" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "environment: $environment\nAND \ncategory: \"ERPNEXT\"",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Database Long Running Queries Logs",
     "type": "logs",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "limit": "500" }, "type": "logs" }
       ],
       "query": "environment: $environment\nAND \ncategory: \"ERPNEXT\"",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "NGINX MONITORING",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "APP NGINX ERRORS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "log_level.keyword",
         "id": "2",
         "settings": {
          "min_doc_count": "1",
          "missing": "N/A",
          "order": "desc",
          "orderBy": "_term",
          "size": "0"
         },
         "type": "terms"
        },
        {
         "field": "category.keyword",
         "id": "5",
         "settings": {
          "min_doc_count": "1",
          "missing": "N/A",
          "order": "desc",
          "orderBy": "_term",
          "size": "0"
         },
         "type": "terms"
        },
        {
         "field": "environment.keyword",
         "id": "6",
         "settings": {
          "min_doc_count": "1",
          "missing": "N/A",
          "order": "desc",
          "orderBy": "_term",
          "size": "0"
         },
         "type": "terms"
        },
        {
         "field": "log_message.keyword",
         "id": "7",
         "settings": {
          "min_doc_count": "1",
          "missing": "Check log as message is too long ",
          "order": "desc",
          "orderBy": "_term",
          "size": "0"
         },
         "type": "terms"
        },
        {
         "field": "process_id.keyword",
         "id": "8",
         "settings": {
          "min_doc_count": "1",
          "missing": "N/A",
          "order": "desc",
          "orderBy": "_term",
          "size": "0"
         },
         "type": "terms"
        },
        {
         "field": "process_instance.keyword",
         "id": "9",
         "settings": {
          "min_doc_count": "1",
          "missing": "N/A",
          "order": "desc",
          "orderBy": "_term",
          "size": "0"
         },
         "type": "terms"
        },
        {
         "field": "request_id.keyword",
         "id": "10",
         "settings": {
          "min_doc_count": "1",
          "missing": "N/A",
          "order": "desc",
          "orderBy": "_term",
          "size": "0"
         },
         "type": "terms"
        },
        {
         "field": "@timestamp",
         "id": "4",
         "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "environment: $environment\nAND \ncategory: \"ERPNEXT\"",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "App Nginx Error Logs",
     "type": "logs",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "limit": "500" }, "type": "logs" }
       ],
       "query": "environment: $environment\nAND \ncategory: \"ERPNEXT\"",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "WEB NGINX ERRORS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "log_level.keyword",
         "id": "2",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "log_message.keyword",
         "id": "5",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "process_id.keyword",
         "id": "6",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "process_instance.keyword",
         "id": "7",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "category.keyword",
         "id": "8",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "environment.keyword",
         "id": "9",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "@timestamp",
         "id": "4",
         "settings": { "interval": "1m", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
         "type": "date_histogram"
        }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "environment: $environment\nAND \ncategory: \"ERPNEXT\"",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Web Error Logs",
     "type": "logs",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "limit": "500" }, "type": "logs" }
       ],
       "query": "environment: $environment\nAND \ncategory: \"ERPNEXT\"",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "EXTRA",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "type": "marcusolsson-dynamictext-panel",
     "gridPos": { "h": 8, "w": 9, "x": 0, "y": 6 },
     "options": {
      "content": "<div class=\"filter-container\" data-panel=\"panel2\">\n  <!-- Field select dropdown for panel2 -->\n  <!-- <select id=\"fieldSelect-panel2\" data-panel=\"panel2\" onchange=\"onFieldSelect('panel2')\">\n    <option value=\"\">Select a field</option>\n    <option value=\"formatted_log_timestamp\">Formatted Timestamp</option>\n    <option value=\"log_timestamp\">Log Timestamp</option>\n    <option value=\"module\">Module</option>\n    <option value=\"log_level\">Log Level</option>\n    <option value=\"log_message\">Log Message</option>\n    <option value=\"payload_json\">Payload</option>\n  </select> -->\n  <select id=\"fieldSelect-panel2\" data-panel=\"panel2\" onchange=\"onFieldSelect('panel2')\">\n    <option value=\"\">Select a field</option>\n    <!-- Dynamically populate dropdown options -->\n  </select>\n\n  <!-- Search filter input for panel2 -->\n  <input type=\"text\" id=\"searchFilter-panel2\" data-panel=\"panel2\" placeholder=\"Search by fields\" oninput=\"filterData('panel2')\">\n\n  <!-- Time range filter dropdown for panel2 -->\n  <select id=\"timeFilter-panel2\" data-panel=\"panel2\" onchange=\"applyTimeFilter('panel2')\">\n    <option value=\"\">Select Time Range</option>\n    <option value=\"1h\">Last 1 Hour</option>\n    <option value=\"1d\">Last 1 Day</option>\n    <option value=\"7d\">Last 7 Days</option>\n    <option value=\"30d\">Last 30 Days</option>\n    <option value=\"5m\">Last 5 Minutes</option>\n    <option value=\"10m\">Last 10 Minutes</option>\n    <option value=\"15m\">Last 15 Minutes</option>\n    <option value=\"20m\">Last 20 Minutes</option>\n    <option value=\"30m\">Last 30 Minutes</option>\n  </select>\n\n  <!-- Download report button for panel2 -->\n  <button class=\"download-button\" data-panel=\"panel2\" onclick=\"generateReport('panel2')\">\n    <span class=\"download-icon\">🡇</span>\n  </button>\n</div>\n\n<!-- Accordion container for panel2 -->\n<div class=\"accordion-container\" id=\"accordionContainer\" data-panel=\"panel2\">\n  {{#each data }}\n  <div class=\"accordion-item\" data-panel=\"panel2\">\n    <button class=\"accordion-header\" data-panel=\"panel2\" onclick=\"toggleAccordion(this)\">\n      <p style=\"display:inline; padding:0px 10px\">{{\"@timestamp\"}} IST &nbsp;||&nbsp; {{formatted_log_timestamp}} UTC</p>\n    </button>\n    <div class=\"accordion-content\" data-panel=\"panel2\">\n      <table class=\"accordion-table\">\n        <tr>\n          <td><strong>Formatted Timestamp:</strong></td>\n          <td>{{formatted_log_timestamp}}</td>\n        </tr>\n        <tr>\n          <td><strong>Log Timestamp:</strong></td>\n          <td>{{ \"@timestamp\"}}</td>\n        </tr>\n        <tr>\n          <td><strong>Module:</strong></td>\n          <td>{{module}}</td>\n        </tr>\n        <tr>\n          <td><strong>Log Level:</strong></td>\n          <td>{{log_level}}</td>\n        </tr>\n        <tr>\n          <td><strong>Log Message:</strong></td>\n          <td>{{log_message}}</td>\n        </tr>\n        <tr>\n          <td><strong>Payload:</strong></td>\n          <td>{{payload_json}}</td>\n        </tr>\n      </table>\n    </div>\n  </div>\n  {{/each}}\n</div>"
     },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "5000" }, "type": "raw_data" }
       ],
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  }
 ]
}