{
 "title": "ERPNEXT INFRA DASHBOARD",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "environment",
    "label": "environment",
    "query": "{\"find\":\"terms\",\"field\":\"environment.keyword\"}"
   },
   {
    "name": "server",
    "label": "server",
    "query": "{\"find\":\"terms\",\"field\":\"host.hostname.keyword\"}"
   },
   {
    "name": "panel_interval",
    "label": "panel interval",
    "query": "1m,2m,5m,10m,20m,30m,1h,2h,3h,4h,6h,12h,1d,2d,3d,4d,7d"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU/MEMORY/PING",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU IDLE PERCENTAGE",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
     "targets": [
      {
       "alias": "{{host.hostname.keyword}}",
       "bucketAggs": [
        {
         "field": "host.hostname.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "category.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "environment.keyword",
         "id": "5",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "10s" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "system.cpu.idle.norm.pct", "id": "1", "settings": { "script": "_value * 100" }, "type": "avg" }
       ],
       "query": "environment: $environment\nAND \ncategory: \"ERPNEXT\" AND host.hostname: $server",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "CPU USER USAGE",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
     "targets": [
      {
       "alias": "{{host.hostname.keyword}}",
       "bucketAggs": [
        {
         "field": "host.hostname.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "category.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "environment.keyword",
         "id": "5",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "10s" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "system.cpu.user.norm.pct", "id": "1", "settings": { "script": "_value * 100" }, "type": "avg" }
       ],
       "query": "environment: $environment\nAND \ncategory: \"ERPNEXT\" AND host.hostname: $server",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "CPU SYSTEM USAGE",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
     "targets": [
      {
       "alias": "{{host.hostname.keyword}}",
       "bucketAggs": [
        {
         "field": "host.hostname.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "category.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        {
         "field": "environment.keyword",
         "id": "5",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "10s" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "system.cpu.system.norm.pct", "id": "1", "settings": { "script": "_value * 100" }, "type": "avg" }
       ],
       "query": "environment: $environment\nAND \ncategory: \"ERPNEXT\" AND host.hostname: $server",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "MEMORY FREE PERCENTAGE",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
     "targets": [
      {
       "alias": "{{host.hostname.keyword}}",
       "bucketAggs": [
        {
         "field": "host.hostname.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "category.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "environment.keyword",
         "id": "5",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "10s" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "system.memory.actual.used.pct", "id": "1", "settings": { "script": "100 - (_value * 100)" }, "type": "avg" }
       ],
       "query": "environment: $environment\nAND \ncategory: \"ERPNEXT\" AND host.hostname: $server",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "SWAP MEMORY USAGE",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
     "targets": [
      {
       "alias": "{{host.hostname.keyword}}",
       "bucketAggs": [
        {
         "field": "host.hostname.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "category.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "environment.keyword",
         "id": "5",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "10s" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "system.memory.used.pct", "id": "1", "settings": { "script": "_value * 100" }, "type": "avg" }
       ],
       "query": "environment: $environment\nAND \ncategory: \"ERPNEXT\" AND host.hostname: $server",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "PING STATUS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
     "targets": [
      {
       "alias": "{{servername.keyword}} = {{url.domain.keyword}}",
       "bucketAggs": [
        {
         "field": "servername.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "url.domain.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "category.keyword",
         "id": "5",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "environment.keyword",
         "id": "6",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "10s" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "latency", "id": "1", "settings": { "script": "_value" }, "type": "avg" }
       ],
       "query": "servername: $server AND environment: $environment\nAND \ncategory: \"ERPNEXT\"",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "APPLICATION DR SYNC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "FRAPPE APP DR SYNC STATUS(SERVER TIME UTC)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "hostname.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        },
        {
         "field": "pid.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        },
        {
         "field": "user.keyword",
         "id": "5",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
         "type": "terms"
        },
        {
         "field": "command.keyword",
         "id": "6",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "log_timestamp.keyword",
         "id": "7",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "category.keyword",
         "id": "8",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "environment.keyword",
         "id": "9",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "5m" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "environment: $environment\nAND \ncategory: \"ERPNEXT\"",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Dr Sync Logs",
     "type": "logs",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "limit": "500" }, "type": "logs" }
       ],
       "query": "environment: $environment\nAND \ncategory: \"ERPNEXT\"",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "BACKUP JOB MONITORING",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "APP JOB MONITORING",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "file_backup_date.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "file_name.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "category.keyword",
         "id": "5",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "environment.keyword",
         "id": "6",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "timeZone": "Asia/Kolkata" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "environment: $environment\nAND \ncategory: \"ERPNEXT\"",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "App Job Monitoring Logs",
     "type": "logs",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "limit": "500" }, "type": "logs" }
       ],
       "query": "environment: $environment\nAND \ncategory: \"ERPNEXT\"",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "DB JOB MONITORING",
     "type": "timeseries",
     "description": "Script",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 11 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "file_backup_date.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "file_name.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "category.keyword",
         "id": "5",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "environment.keyword",
         "id": "6",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "timeZone": "Asia/Kolkata" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "environment: $environment\nAND \ncategory: \"ERPNEXT\"",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "SUCCESSFUL BACKUP COUNT",
     "type": "timeseries",
     "description": "Filebeat",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 11 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "log.file.path.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "log_message.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "category.keyword",
         "id": "5",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "environment.keyword",
         "id": "6",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "timeZone": "Asia/Kolkata" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "environment: $environment\nAND \ncategory: \"ERPNEXT\"",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "ERROR WHILE BACKUP COUNT",
     "type": "timeseries",
     "description": "Filebeat",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 11 },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "log.file.path.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "log_message.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "timeZone": "Asia/Kolkata" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "id": "1", "type": "count" }
       ],
       "query": "environment: $environment\nAND \ncategory: \"ERPNEXT\"",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Db Job Monitoring Logs",
     "type": "logs",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 11 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "limit": "500" }, "type": "logs" }
       ],
       "query": "environment: $environment\nAND \ncategory: \"ERPNEXT\"",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "REDIS MONITORING",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "REDIS MONITORING",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "targets": [
      {
       "alias": "{{process_name.keyword}}",
       "bucketAggs": [
        {
         "field": "process_name.keyword",
         "id": "3",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "category.keyword",
         "id": "4",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        {
         "field": "environment.keyword",
         "id": "5",
         "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
         "type": "terms"
        },
        { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "timeZone": "utc" }, "type": "date_histogram" }
       ],
       "metrics": [
        { "field": "status_number", "id": "1", "type": "avg" }
       ],
       "query": "environment: $environment\nAND \ncategory: \"ERPNEXT\"",
       "timeField": "@timestamp"
      }
     ]
    },
    {
     "title": "Redis Monitoring Logs",
     "type": "logs",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "limit": "500" }, "type": "logs" }
       ],
       "query": "environment: $environment\nAND \ncategory: \"ERPNEXT\"",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  }
 ]
}